language: node_js

sudo: false

node_js:
  - 'node'
  - '14'
  - '13'
  - '12'
  - '11'
  - '10'
  - '13.6.0'

after_success:
  - ./bin/codecov -e TRAVIS_NODE_VERSION -f coverage/*.json
  - ./bin/codecov -e TRAVIS_NODE_VERSION
